"""initial schema

Revision ID: 418cb89b6b6b
Revises: 
Create Date: 2025-12-02 13:16:58.188901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418cb89b6b6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('tax_number', sa.String(length=64), nullable=True),
    sa.Column('tax_card_file_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'ACTIVE', 'SUSPENDED', 'CHURNED', name='client_status'), server_default='LEAD', nullable=False),
    sa.Column('workspace_domain', sa.String(length=255), nullable=True),
    sa.Column('has_portal_account', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('google_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_billing_period', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('google_sku', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('raw_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('xendit_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_source_event_type', 'webhook_events', ['source', 'event_type'], unique=False)
    op.create_index('ix_webhook_events_xendit_invoice_id', 'webhook_events', ['xendit_invoice_id'], unique=False)
    op.create_index('ix_webhook_events_xendit_subscription_id', 'webhook_events', ['xendit_subscription_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'SALES', 'ADMIN', 'FINANCE', name='user_role'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wallet_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_accounts_client_id'), 'wallet_accounts', ['client_id'], unique=True)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='email_direction_enum'), nullable=False),
    sa.Column('related_type', sa.Enum('QUOTATION', 'INVOICE_REQUEST', 'CLIENT_MAIL', 'REMINDER', 'PAYMENT_STATUS', 'OTHER', name='email_related_type_enum'), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_generated_body', sa.Text(), nullable=True),
    sa.Column('final_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'FAILED', 'RECEIVED', 'PARSED', name='email_status_enum'), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachments_meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_logs_direction', 'email_logs', ['direction'], unique=False)
    op.create_index('ix_email_logs_gmail_message_id', 'email_logs', ['gmail_message_id'], unique=False)
    op.create_index('ix_email_logs_related_type_related_id', 'email_logs', ['related_type', 'related_id'], unique=False)
    op.create_index('ix_email_logs_user_id', 'email_logs', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_ACTIVATION', 'ACTIVE', 'SUSPENDED', 'CANCELLED', 'EXPIRED', name='subscription_status_enum', native_enum=False), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'YEARLY', name='billing_period_enum', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('payment_method_type', sa.Enum('XENDIT_SUBSCRIPTION', 'MANUAL', 'WALLET', name='subscription_payment_method_enum', native_enum=False), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('xendit_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TOPUP', 'CHARGE', 'REFUND', 'ADJUSTMENT', name='wallet_transaction_type'), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='wallet_transaction_direction'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('related_type', sa.Enum('PAYMENT', 'SUBSCRIPTION', 'MANUAL', name='wallet_transaction_related_type'), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['wallet_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_related_id'), 'wallet_transactions', ['related_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_account_id'), 'wallet_transactions', ['wallet_account_id'], unique=False)
    op.create_table('billing_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVOICE_REQUESTED', 'INVOICED', 'PAID', 'FAILED', 'CANCELLED', name='billing_cycle_status'), nullable=False),
    sa.Column('is_initial_cycle', sa.Boolean(), nullable=False),
    sa.Column('quoted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invoice_number_external', sa.String(length=100), nullable=True),
    sa.Column('invoice_file_url', sa.String(length=2048), nullable=True),
    sa.Column('tax_invoice_file_url', sa.String(length=2048), nullable=True),
    sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_cycles_subscription_id'), 'billing_cycles', ['subscription_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('sales_user_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('client_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_amount_client', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_subscription_id', sa.UUID(), nullable=True),
    sa.Column('cosmic_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cosmic_id')
    )
    op.create_index(op.f('ix_quotations_gmail_thread_id'), 'quotations', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_quotations_number'), 'quotations', ['number'], unique=True)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('subscription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('provisioning_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='provisioning_status_enum', native_enum=False), nullable=False),
    sa.Column('google_workspace_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('gcp_resource_id', sa.String(length=255), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('billing_cycle_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum'), nullable=False),
    sa.Column('method', sa.Enum('XENDIT_EWALLET', 'XENDIT_CC', 'XENDIT_VA', 'MANUAL', name='payment_method_enum'), nullable=False),
    sa.Column('xendit_payment_id', sa.String(length=255), nullable=True),
    sa.Column('xendit_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['billing_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_billing_cycle_id'), 'payments', ['billing_cycle_id'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_xendit_payment_id'), 'payments', ['xendit_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_xendit_subscription_id'), 'payments', ['xendit_subscription_id'], unique=False)
    op.create_table('provisioning_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('ACTIVATE', 'SUSPEND', 'CHANGE_QUANTITY', 'TERMINATE', name='provisioning_action_enum'), nullable=False),
    sa.Column('target_system', sa.Enum('GWORKSPACE', 'GCP', name='provisioning_target_system_enum'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='provisioning_status_enum'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_item_id'], ['subscription_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_price_client', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal_amount_client', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_product_id'), 'quotation_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_product_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_table('provisioning_tasks')
    op.drop_index(op.f('ix_payments_xendit_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_xendit_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_cycle_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('subscription_items')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_gmail_thread_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_billing_cycles_subscription_id'), table_name='billing_cycles')
    op.drop_table('billing_cycles')
    op.drop_index(op.f('ix_wallet_transactions_wallet_account_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_related_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_table('subscriptions')
    op.drop_index('ix_email_logs_user_id', table_name='email_logs')
    op.drop_index('ix_email_logs_related_type_related_id', table_name='email_logs')
    op.drop_index('ix_email_logs_gmail_message_id', table_name='email_logs')
    op.drop_index('ix_email_logs_direction', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_wallet_accounts_client_id'), table_name='wallet_accounts')
    op.drop_table('wallet_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_webhook_events_xendit_subscription_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_xendit_invoice_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_source_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('products')
    op.drop_table('clients')
    # ### end Alembic commands ###
